// Source for the minified theme-extension asset generated by `npm run build:extension`.
import DOMPurify from "dompurify";
import { createPopupSessionState } from "./welcome-popup-state.mjs";
import { responseFailure, validationReasons } from "./welcome-analytics.mjs";
import { createCartRecovery } from "./cart-recovery.mjs";

(() => {
  const formEndpoint = "/apps/ermes/signup-form";
  const analyticsEndpoint = "/apps/ermes/newsletter/event";
  const subscribeEndpoint = "/apps/ermes/newsletter/subscribe";
  const supportedSchemaVersion = 1;
  const visitorStorageKey = "ermes-messaging:visitor-id";
  const previewStorageKey = "ermes-messaging:popup-preview";
  const previewParam = "ermes_popup_preview";
  const previewToken = (() => {
    const url = new URL(location.href);
    const supplied = url.searchParams.get(previewParam);
    try {
      if (supplied) window.sessionStorage.setItem(previewStorageKey, supplied);
      return supplied || window.sessionStorage.getItem(previewStorageKey);
    } catch { return supplied; }
  })();
  const previewBanner = (label) => {
    let banner = document.getElementById("ermes-popup-preview-banner");
    if (banner) return;
    banner = document.createElement("div");
    banner.id = "ermes-popup-preview-banner";
    banner.setAttribute("role", "status");
    banner.style.cssText = "position:fixed;top:0;left:0;right:0;z-index:2147483647;background:#172554;color:white;padding:12px 16px;font:14px/1.4 sans-serif;display:flex;gap:16px;align-items:center;justify-content:space-between";
    const text = document.createElement("span");
    text.textContent = label;
    const exit = document.createElement("button");
    exit.type = "button";
    exit.textContent = "Exit preview";
    exit.style.cssText = "background:white;color:#172554;border:0;border-radius:4px;padding:8px 12px;cursor:pointer;white-space:nowrap";
    exit.addEventListener("click", () => {
      try { window.sessionStorage.removeItem(previewStorageKey); } catch { /* No storage. */ }
      const url = new URL(location.href);
      url.searchParams.delete(previewParam);
      location.replace(url.toString());
    });
    banner.append(text, exit);
    document.body.append(banner);
  };

  // Load Shopify's supported consent API; absence still means no forwarding.
  const privacyReady = new Promise((resolve) => {
    if (window.Shopify?.customerPrivacy || !window.Shopify?.loadFeatures) return resolve();
    const timer = window.setTimeout(resolve, 1500);
    try {
      window.Shopify.loadFeatures([{ name: "consent-tracking-api", version: "0.1" }], () => {
        window.clearTimeout(timer);
        resolve();
      });
    } catch { window.clearTimeout(timer); resolve(); }
  });
  const cartRecovery = createCartRecovery({ window, document, fetch });
  if (!previewToken) void privacyReady.then(() => cartRecovery.start());

  const randomId = () =>
    window.crypto?.randomUUID?.() ||
    `${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random()
      .toString(36)
      .slice(2)}`;

  const visitorId = () => {
    try {
      if (window.Shopify?.customerPrivacy?.analyticsProcessingAllowed?.() !== true) {
        window.__ermesMessagingVisitorId ||= randomId();
        return window.__ermesMessagingVisitorId;
      }
      const existing = window.localStorage.getItem(visitorStorageKey);
      if (existing) return existing;
      const created = randomId();
      window.localStorage.setItem(visitorStorageKey, created);
      return created;
    } catch {
      // Storage-restricted visitors still get stable assignment for this page.
      window.__ermesMessagingVisitorId ||= randomId();
      return window.__ermesMessagingVisitorId;
    }
  };

  const storedUntil = (key) => {
    try {
      return Number(window.localStorage.getItem(key) || 0);
    } catch {
      return 0;
    }
  };

  const hideUntil = (key, days) => {
    try {
      window.localStorage.setItem(
        key,
        String(Date.now() + days * 24 * 60 * 60 * 1000),
      );
    } catch {
      // Privacy modes can disable storage; the popup still remains functional.
    }
  };

  const storedFlag = (key) => {
    try {
      return window.localStorage.getItem(key) === "true";
    } catch {
      return false;
    }
  };

  const rememberFlag = (key) => {
    try {
      window.localStorage.setItem(key, "true");
    } catch {
      // Privacy modes can disable storage; the popup still remains functional.
    }
  };

  const number = (value, fallback) =>
    Number.isFinite(Number(value)) ? Number(value) : fallback;

  const px = (value) => (value == null ? "" : `${number(value, 0)}px`);

  const applyStyles = (element, styles) => {
    Object.entries(styles).forEach(([key, value]) => {
      if (value !== undefined && value !== null && value !== "") {
        if (key.startsWith("--")) {
          element.style.setProperty(key, String(value));
        } else {
          element.style[key] = String(value);
        }
      }
    });
  };

  const visibleOnDevice = (styles = {}) => {
    const mobile = window.matchMedia("(max-width: 749px)").matches;
    return !(mobile ? styles.hideOnMobile : styles.hideOnDesktop);
  };

  const textStyles = (
    styles,
    theme,
    fallbackColor,
    fallbackSize,
    fallbackMarginBottom,
  ) => ({
    color: styles.color || theme.textColor || fallbackColor,
    fontFamily: styles.fontFamily || theme.fontFamily || "",
    fontSize: px(styles.fontSize ?? fallbackSize),
    fontWeight:
      styles.fontWeight === "bold"
        ? "700"
        : styles.fontWeight === "medium"
          ? "500"
          : "400",
    letterSpacing:
      styles.letterSpacing == null ? "" : px(styles.letterSpacing),
    lineHeight: styles.lineHeight || "1.4",
    marginBottom: px(styles.marginBottom ?? fallbackMarginBottom),
    marginTop: px(styles.marginTop ?? 0),
    paddingBottom: px(styles.paddingY),
    paddingLeft: px(styles.paddingX),
    paddingRight: px(styles.paddingX),
    paddingTop: px(styles.paddingY),
    textAlign: styles.align || "center",
  });

  const fieldStyles = (styles, theme) => ({
    background: "#ffffff",
    border: `${number(styles.borderWidth, 1)}px solid ${
      styles.borderColor || "#d4d4d4"
    }`,
    borderRadius: px(styles.radius ?? theme.buttonRadius ?? 0),
    boxSizing: "border-box",
    fontFamily: styles.fontFamily || theme.fontFamily || "",
    fontSize: "14px",
    height: "44px",
    marginBottom: px(styles.marginBottom ?? 10),
    marginTop: px(styles.marginTop ?? 0),
    padding: "0 14px",
    width: "100%",
  });

  const renderBlock = (block, theme) => {
    const styles = block.styles || {};
    if (!visibleOnDevice(styles)) return null;

    let element;
    switch (block.type) {
      case "heading":
        element = document.createElement("div");
        element.textContent = block.text || "";
        applyStyles(
          element,
          textStyles(
            styles,
            theme,
            theme.headingColor || theme.textColor || "#111111",
            18,
            8,
          ),
        );
        return element;
      case "text":
        element = document.createElement("p");
        element.textContent = block.text || "";
        applyStyles(
          element,
          textStyles(styles, theme, theme.textColor || "#666666", 13, 12),
        );
        return element;
      case "image": {
        if (!block.src) return null;
        const image = document.createElement("img");
        image.alt = block.text || "";
        image.loading = "eager";
        image.src = block.src;
        applyStyles(image, {
          borderRadius: px(styles.radius ?? 0),
          display: "block",
          height: styles.height == null ? "auto" : px(styles.height),
          marginBottom: px(styles.marginBottom ?? 0),
          marginTop: px(styles.marginTop ?? 0),
          objectFit: styles.objectFit || "cover",
          width: "100%",
        });
        if (!styles.href) return image;
        element = document.createElement("a");
        element.href = styles.href;
        element.rel = "noreferrer";
        element.target = "_blank";
        element.append(image);
        return element;
      }
      case "email_input":
      case "name_field":
        element = document.createElement("input");
        element.autocomplete =
          block.type === "email_input" ? "email" : "given-name";
        element.name =
          block.type === "email_input" ? "email" : "first_name";
        element.placeholder =
          block.text ||
          (block.type === "email_input" ? "Email" : "First name");
        element.required = block.type === "email_input";
        element.type = block.type === "email_input" ? "email" : "text";
        applyStyles(element, fieldStyles(styles, theme));
        return element;
      case "consent": {
        element = document.createElement("label");
        const checkbox = document.createElement("input");
        const copy = document.createElement("span");
        checkbox.name = "consent";
        checkbox.required = true;
        checkbox.type = "checkbox";
        copy.textContent =
          block.text || "I agree to receive marketing emails.";
        element.append(checkbox, copy);
        applyStyles(element, {
          alignItems: "flex-start",
          color: styles.color || theme.textColor || "#666666",
          display: "flex",
          fontFamily: styles.fontFamily || theme.fontFamily || "",
          fontSize: px(styles.fontSize ?? 12),
          gap: "8px",
          lineHeight: styles.lineHeight || "1.4",
          marginBottom: px(styles.marginBottom ?? 10),
          marginTop: px(styles.marginTop ?? 0),
          textAlign: "left",
        });
        checkbox.style.marginTop = "3px";
        return element;
      }
      case "button":
        element = document.createElement("button");
        element.textContent = block.text || "Subscribe";
        element.type = "submit";
        applyStyles(element, {
          background:
            styles.background || theme.buttonBackground || "#111111",
          border: "none",
          borderRadius: px(styles.radius ?? theme.buttonRadius ?? 0),
          color: styles.color || theme.buttonColor || "#ffffff",
          cursor: "pointer",
          fontFamily: styles.fontFamily || theme.fontFamily || "",
          fontSize: px(styles.fontSize ?? 13),
          fontWeight: "600",
          height: "44px",
          letterSpacing:
            styles.letterSpacing == null
              ? "0.06em"
              : px(styles.letterSpacing),
          marginBottom: px(styles.marginBottom ?? 0),
          marginTop: px(styles.marginTop ?? 0),
          width: styles.fullWidth === false ? "auto" : "100%",
        });
        return element;
      case "divider":
        element = document.createElement("hr");
        applyStyles(element, {
          border: "none",
          borderTop: `${number(styles.borderWidth, 1)}px solid ${
            styles.borderColor || "#e5e5e5"
          }`,
          margin: `${number(styles.size, 12)}px 0`,
        });
        return element;
      case "spacer":
        element = document.createElement("div");
        element.style.height = px(styles.size ?? 16);
        return element;
      case "html":
        element = document.createElement("div");
        element.innerHTML = DOMPurify.sanitize(block.text || "");
        return element;
      default:
        return null;
    }
  };

  const renderStep = (form, signupDocument, kind) => {
    form.replaceChildren();
    if (
      kind === "opt_in" &&
      signupDocument.mode === "html" &&
      typeof signupDocument.html === "string"
    ) {
      form.innerHTML = DOMPurify.sanitize(signupDocument.html);
      return;
    }
    const step = (signupDocument.steps || []).find(
      (candidate) => candidate.kind === kind,
    );
    const blocks = step?.blocks || (kind === "already_subscribed"
      ? [
          {
            id: "fallback_already_subscribed_heading",
            type: "heading",
            text: "You're already on the list",
            styles: { align: "center", fontSize: 20, fontWeight: "medium" },
          },
          {
            id: "fallback_already_subscribed_text",
            type: "text",
            text: "No need to sign up again — we'll keep you posted.",
            styles: { align: "center", color: "#666666" },
          },
        ]
      : []);
    blocks.forEach((block) => {
      const element = renderBlock(block, signupDocument.styles || {});
      if (element) form.append(element);
    });
  };

  const audienceMatches = (audience, device, customerLoggedIn) => {
    if (!audience) return true;
    const includedPaths = Array.isArray(audience.page_paths)
      ? audience.page_paths.filter(Boolean)
      : [];
    const excludedPaths = Array.isArray(audience.excluded_page_paths)
      ? audience.excluded_page_paths.filter(Boolean)
      : [];
    const devices = Array.isArray(audience.devices)
      ? audience.devices
      : ["desktop", "mobile"];
    return !(
      (includedPaths.length &&
        !includedPaths.some((path) => location.pathname.startsWith(path))) ||
      excludedPaths.some((path) => location.pathname.startsWith(path)) ||
      !devices.includes(device) ||
      (audience.hide_when_logged_in && customerLoggedIn)
    );
  };

  const fetchSignupForm = async ({ customerLoggedIn, device, visitor }) => {
    const response = await fetch(formEndpoint, {
      body: JSON.stringify({
        preview_token: previewToken || undefined,
        customer_logged_in: customerLoggedIn,
        device,
        page_path: location.pathname.slice(0, 500) || "/",
        visitor_id: visitor,
      }),
      credentials: "same-origin",
      headers: {
        accept: "application/json",
        "content-type": "application/json",
      },
      method: "POST",
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(previewToken ? error.detail || "Popup preview is unavailable." : "Newsletter signup is unavailable.");
    }
    const payload = await response.json();
    const form = payload?.form;
    if (!form) return null;
    if (
      !form.document ||
      number(form.document.schema_version, 0) > supportedSchemaVersion ||
      !Array.isArray(form.document.steps)
    ) {
      throw new Error("Newsletter signup has an unsupported format.");
    }
    return form;
  };

  const bindPopup = async (root) => {
    if (!(root instanceof HTMLElement) || root.dataset.bound === "true") return;
    root.dataset.bound = "true";

    const designMode = Boolean(window.Shopify?.designMode);
    const currentDevice = window.matchMedia("(max-width: 749px)").matches
      ? "mobile"
      : "desktop";
    const customerLoggedIn = root.dataset.customerLoggedIn === "true";
    await privacyReady;
    const currentVisitorId = previewToken ? randomId() : visitorId();

    let signupForm;
    try {
      signupForm = await fetchSignupForm({
        customerLoggedIn,
        device: currentDevice,
        visitor: currentVisitorId,
      });
    } catch (error) {
      if (previewToken) previewBanner(error instanceof Error ? error.message : "Popup preview is unavailable.");
      console.warn("[Ermes welcome popup]", error);
      return;
    }
    if (!signupForm) return;
    const previewMode = Boolean(signupForm.preview);
    const isolatedPreview = designMode || previewMode;
    if (previewMode) {
      previewBanner(`Popup preview: ${signupForm.preview.name}. Popup analytics and subscriptions are off.`);
      const cleanUrl = new URL(location.href);
      cleanUrl.searchParams.delete(previewParam);
      window.history.replaceState(window.history.state, "", cleanUrl);
    }

    const signupDocument = signupForm.document;
    const formType = signupForm.type === "flyout" ? "flyout" : "popup";
    const targeting = signupDocument.targeting || {};
    if (
      !isolatedPreview &&
      !audienceMatches(
        signupForm.experiment?.shared_audience,
        currentDevice,
        customerLoggedIn,
      )
    ) {
      return;
    }

    const analyticsContext = {
      analytics_token: signupForm.analytics_token,
      device: currentDevice,
      form_id: signupForm.id,
      form_version_id: signupForm.version_id || undefined,
      page_path: location.pathname.slice(0, 500),
      visitor_id: currentVisitorId,
    };
    const eligibleEventId = randomId();
    const viewEventId = randomId();
    const clickEventId = randomId();
    const submissionEventId = randomId();
    analyticsContext.impression_id = viewEventId;
    const analyticsAllowed = () => {
      try {
        return window.Shopify?.customerPrivacy?.analyticsProcessingAllowed?.() === true;
      } catch { return false; }
    };
    const publish = (eventType, eventId, details = {}) => {
      if (isolatedPreview) return;
      try {
        // Shopify gates its pixel on analytics consent. Publish only after Ermes
        // has accepted the event so the pixel can link it without a second count.
        Promise.resolve(window.Shopify?.analytics?.publish?.("ermes:signup_form", {
          event_id: eventId,
          event_type: eventType,
          form_id: signupForm.id,
          visitor_id: currentVisitorId,
          device: currentDevice,
          impression_id: viewEventId,
          details,
        })).catch(() => undefined);
      } catch { /* Analytics must never interrupt subscription or dismissal. */ }
    };
    const track = (eventType, eventId, details = {}) =>
      isolatedPreview ? Promise.resolve() : fetch(analyticsEndpoint, {
        body: JSON.stringify({
          ...analyticsContext,
          analytics_allowed: analyticsAllowed(),
          details,
          event_id: eventId,
          event_type: eventType,
        }),
        headers: { "content-type": "application/json" },
        keepalive: true,
        method: "POST",
      }).then((response) => {
        if (response.ok) publish(eventType, eventId, details);
      }).catch(() => undefined);

    if (
      !isolatedPreview &&
      signupForm.experiment?.exposure_event === "eligible"
    ) {
      void track("eligible", eligibleEventId);
    }

    const includedPaths = Array.isArray(targeting.page_paths)
      ? targeting.page_paths.filter(Boolean)
      : [];
    const excludedPaths = Array.isArray(targeting.excluded_page_paths)
      ? targeting.excluded_page_paths.filter(Boolean)
      : [];
    const devices = Array.isArray(targeting.devices)
      ? targeting.devices
      : ["desktop", "mobile"];
    if (
      !isolatedPreview &&
      ((includedPaths.length &&
        !includedPaths.some((path) =>
          location.pathname.startsWith(path),
        )) ||
        excludedPaths.some((path) =>
          location.pathname.startsWith(path),
        ) ||
        !devices.includes(currentDevice) ||
        (targeting.hide_when_logged_in &&
          customerLoggedIn))
    ) {
      return;
    }

    const storageKey = `${root.dataset.storagePrefix || "ermes-welcome-popup"}:${
      signupForm.id
    }`;
    const closedUntilKey = `${storageKey}:closed-until`;
    const submittedKey = `${storageKey}:submitted`;
    const popupSession = createPopupSessionState();
    const isPersistentlySuppressed = () =>
      !isolatedPreview &&
      ((targeting.hide_after_submit !== false &&
        storedFlag(submittedKey)) ||
        Math.max(
          storedUntil(storageKey),
          storedUntil(closedUntilKey),
        ) > Date.now());
    if (!popupSession.canOpen(isPersistentlySuppressed())) {
      return;
    }

    const dialog = root.querySelector(".ermes-welcome__dialog");
    const backdrop = root.querySelector("[data-ermes-welcome-backdrop]");
    const closeButton = root.querySelector("[data-ermes-welcome-close-button]");
    const form = root.querySelector("[data-ermes-welcome-form]");
    const image = root.querySelector("[data-ermes-welcome-image]");
    const message = root.querySelector("[data-ermes-welcome-message]");
    const teaser = document.querySelector(
      `[data-ermes-welcome-teaser="${CSS.escape(root.id)}"]`,
    );
    const teaserContent = teaser?.querySelector(
      "[data-ermes-welcome-teaser-content]",
    );
    const teaserOpen = teaser?.querySelector(
      "[data-ermes-welcome-teaser-open]",
    );
    if (
      !(dialog instanceof HTMLElement) ||
      !(form instanceof HTMLFormElement) ||
      !(message instanceof HTMLElement)
    ) {
      return;
    }

    const theme = signupDocument.styles || {};
    const closeButtonDevices = Array.isArray(targeting.close_button_devices)
      ? targeting.close_button_devices
      : ["desktop", "mobile"];
    const outsideDismissDevices = Array.isArray(targeting.dismiss_on_outside_devices)
      ? targeting.dismiss_on_outside_devices
      : ["desktop", "mobile"];
    root.dataset.formType = formType;
    root.dataset.formMode = signupDocument.mode || "blocks";
    dialog.setAttribute("aria-modal", formType === "popup" ? "true" : "false");
    if (backdrop instanceof HTMLElement) {
      backdrop.hidden = formType === "flyout";
    }
    if (closeButton instanceof HTMLButtonElement) {
      const showCloseButton = closeButtonDevices.includes(currentDevice);
      closeButton.hidden = !showCloseButton;
      closeButton.disabled = !showCloseButton;
    }
    applyStyles(dialog, {
      "--ermes-welcome-background": theme.background || "#ffffff",
      "--ermes-welcome-button": theme.buttonBackground || "#111111",
      "--ermes-welcome-button-text": theme.buttonColor || "#ffffff",
      "--ermes-welcome-text": theme.textColor || "#111111",
      "--ermes-welcome-max-width": px(theme.width || 480),
    });
    if (teaser instanceof HTMLElement) {
      applyStyles(teaser, {
        "--ermes-welcome-background": theme.background || "#ffffff",
        "--ermes-welcome-text": theme.textColor || "#111111",
      });
    }
    if (
      image instanceof HTMLImageElement &&
      theme.image_url &&
      (currentDevice === "desktop" || theme.image_on_mobile === true)
    ) {
      // Eligibility has passed. Download while the popup waits for its display trigger.
      image.loading = "eager";
      image.src = theme.image_url;
      image.hidden = false;
    }
    if (typeof signupDocument.css === "string" && signupDocument.css.trim()) {
      const style = document.createElement("style");
      style.textContent = signupDocument.css;
      root.prepend(style);
    }

    renderStep(form, signupDocument, "opt_in");
    const teaserStep = (signupDocument.steps || []).find(
      (candidate) => candidate.kind === "teaser",
    );
    const hasTeaser = Boolean(teaserStep?.blocks?.length);
    if (hasTeaser && teaserContent instanceof HTMLElement) {
      renderStep(teaserContent, signupDocument, "teaser");
      teaserContent.inert = true;
    }
    const honeypot = document.createElement("input");
    honeypot.autocomplete = "off";
    honeypot.className = "ermes-welcome__honeypot";
    honeypot.name = "company";
    honeypot.tabIndex = -1;
    honeypot.type = "text";
    form.append(honeypot);

    const cooldownDays = Math.max(
      0,
      number(targeting.cooldown_days, 30),
    );
    let previousFocus = null;
    let impressionRecorded = false;
    let clickRecorded = false;
    let submissionComplete = false;
    const diagnosticsRecorded = new Set();
    const recordDiagnostic = (eventType, details = {}) => {
      const key = `${eventType}:${(details.reasons || []).join(",")}:${details.http_status || ""}`;
      if (isolatedPreview || !impressionRecorded || diagnosticsRecorded.has(key)) return;
      diagnosticsRecorded.add(key);
      void track(eventType, randomId(), details);
    };
    const recordClick = () => {
      if (clickRecorded || isolatedPreview) return;
      clickRecorded = true;
      void track("clicked", clickEventId);
    };

    const open = () => {
      if (
        !root.hidden ||
        !popupSession.canOpen(isPersistentlySuppressed())
      ) {
        return;
      }
      previousFocus = document.activeElement;
      if (teaser instanceof HTMLElement) teaser.hidden = true;
      root.hidden = false;
      if (formType === "popup") {
        document.documentElement.classList.add("ermes-welcome-open");
      }
      form.querySelector('input[name="email"]')?.focus();
      if (!impressionRecorded && !isolatedPreview) {
        impressionRecorded = true;
        void track("viewed", viewEventId);
      }
    };

    const close = (remember = true, dismissalEvent = null) => {
      if (root.hidden) return;
      if (dismissalEvent && !submissionComplete) recordDiagnostic(dismissalEvent);
      popupSession.dismiss();
      root.hidden = true;
      if (teaser instanceof HTMLElement) teaser.hidden = true;
      document.documentElement.classList.remove("ermes-welcome-open");
      if (remember && !isolatedPreview) hideUntil(closedUntilKey, cooldownDays);
      if (previousFocus instanceof HTMLElement) previousFocus.focus();
    };

    if (closeButton instanceof HTMLButtonElement) {
      closeButton.addEventListener("click", () => close(true, "dismissed_close"));
    }
    if (
      formType === "popup" &&
      backdrop instanceof HTMLElement &&
      outsideDismissDevices.includes(currentDevice)
    ) {
      backdrop.addEventListener("click", () => close(true, "dismissed_backdrop"));
    }
    if (teaserOpen instanceof HTMLButtonElement) {
      teaserOpen.addEventListener("click", open);
    }
    root.addEventListener("keydown", (event) => {
      if (event.key === "Escape") close(true, "dismissed_escape");
      if (event.key !== "Tab" || formType !== "popup") return;
      const focusable = Array.from(
        dialog.querySelectorAll(
          'button:not([disabled]), input:not([disabled]), [href], [tabindex]:not([tabindex="-1"])',
        ),
      );
      if (!focusable.length) return;
      const first = focusable[0];
      const last = focusable[focusable.length - 1];
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    });

    form.addEventListener("click", (event) => {
      const target = event.target;
      if (!(target instanceof Element)) return;
      if (
        target.closest(
          'button[type="submit"], button:not([type]), input[type="submit"]',
        )
      ) {
        recordClick();
      }
    });

    form.addEventListener("submit", async (event) => {
      event.preventDefault();
      if (previewMode) {
        submissionComplete = true;
        renderStep(form, signupDocument, "success");
        if (image instanceof HTMLImageElement) image.hidden = true;
        message.textContent = "Preview only — no subscription was created.";
        return;
      }
      // Keyboard submission may not dispatch a click in every browser.
      recordClick();
      const values = new FormData(form);
      if (values.get("company")) {
        recordDiagnostic("validation_failed", { reasons: ["bot_detected"] });
        return close();
      }
      if (!form.checkValidity()) {
        recordDiagnostic("validation_failed", { reasons: validationReasons(form) });
        form.reportValidity();
        return;
      }
      const email = String(values.get("email") || "").trim();
      const submit = form.querySelector('button[type="submit"]');
      if (submit instanceof HTMLButtonElement) submit.disabled = true;
      message.textContent = "";
      const controller = new AbortController();
      const timeout = window.setTimeout(() => controller.abort(), 20000);
      let failure = { reasons: ["network_error"], submission_event_id: submissionEventId };
      try {
        const recoveryContext = await cartRecovery.signupContext();
        const response = await fetch(subscribeEndpoint, {
          body: JSON.stringify({
            ...recoveryContext,
            analytics_allowed: analyticsAllowed(),
            impression_id: viewEventId,
            analytics_event_id: submissionEventId,
            analytics_token: analyticsContext.analytics_token,
            device: analyticsContext.device,
            email,
            consent: true,
            first_name: String(values.get("first_name") || "").trim() || undefined,
            form_id: signupForm.id,
            form_version_id: analyticsContext.form_version_id,
            page_path: analyticsContext.page_path,
            source: `shopify-welcome-${formType}`,
            visitor_id: analyticsContext.visitor_id,
          }),
          headers: { "content-type": "application/json" },
          method: "POST",
          signal: controller.signal,
        });
        const payload = await response.json().catch(() => ({}));
        if (!response.ok) {
          failure = { ...failure, reasons: [responseFailure(response.status)], http_status: response.status };
          throw new Error(typeof payload.detail === "string" ? payload.detail : "Please try again.");
        }
        if (payload.success !== true) {
          failure = { ...failure, reasons: ["invalid_response"], http_status: response.status };
          throw new Error("We could not confirm your subscription. Please try again.");
        }
        submissionComplete = true;
        if (payload.recovery_identity_token) cartRecovery.remember(payload.recovery_identity_token);
        publish("submitted", submissionEventId, { already_subscribed: Boolean(payload.already_subscribed) });
        renderStep(
          form,
          signupDocument,
          payload.already_subscribed ? "already_subscribed" : "success",
        );
        if (image instanceof HTMLImageElement) image.hidden = true;
        message.textContent = "";
        rememberFlag(submittedKey);
        window.setTimeout(() => close(false), 3000);
      } catch (error) {
        if (controller.signal.aborted) failure = { ...failure, reasons: ["timeout"] };
        if (!submissionComplete) recordDiagnostic("submit_failed", failure);
        message.textContent =
          controller.signal.aborted ? "The request timed out. Please try again." :
            error instanceof Error ? error.message : "Please try again.";
        if (submit instanceof HTMLButtonElement) submit.disabled = false;
      } finally {
        window.clearTimeout(timeout);
      }
    });

    if (isolatedPreview) {
      open();
      return;
    }

    if (hasTeaser && teaser instanceof HTMLElement) {
      teaser.hidden = false;
    }

    const triggers =
      Array.isArray(targeting.triggers) && targeting.triggers.length
        ? [...new Set(targeting.triggers)]
        : [targeting.trigger || "time"];
    const metTriggers = new Set();
    const markTriggerMet = (trigger) => {
      metTriggers.add(trigger);
      if (
        targeting.trigger_match === "all"
          ? triggers.every((candidate) => metTriggers.has(candidate))
          : metTriggers.size > 0
      ) {
        open();
      }
    };

    if (triggers.includes("time")) {
      window.setTimeout(
        () => markTriggerMet("time"),
        Math.max(0, number(targeting.delay_ms, 5000)),
      );
    }

    if (triggers.includes("scroll")) {
      const threshold = Math.min(
        100,
        Math.max(1, number(targeting.scroll_percent, 50)),
      );
      const onScroll = () => {
        const available =
          document.documentElement.scrollHeight - window.innerHeight;
        const progress = available > 0 ? (window.scrollY / available) * 100 : 100;
        if (progress >= threshold) {
          window.removeEventListener("scroll", onScroll);
          markTriggerMet("scroll");
        }
      };
      window.addEventListener("scroll", onScroll, { passive: true });
      onScroll();
    }

    if (triggers.includes("exit_intent")) {
      const onExit = (event) => {
        if (event.clientY > 0) return;
        document.removeEventListener("mouseout", onExit);
        markTriggerMet("exit_intent");
      };
      document.addEventListener("mouseout", onExit);

      let touchStartY = null;
      const onTouchStart = (event) => {
        touchStartY = event.touches[0]?.clientY ?? null;
      };
      const onTouchMove = (event) => {
        const currentY = event.touches[0]?.clientY;
        if (
          touchStartY == null ||
          currentY == null ||
          window.scrollY < 100 ||
          currentY - touchStartY < 80
        ) {
          return;
        }
        document.removeEventListener("touchstart", onTouchStart);
        document.removeEventListener("touchmove", onTouchMove);
        markTriggerMet("exit_intent");
      };
      document.addEventListener("touchstart", onTouchStart, {
        passive: true,
      });
      document.addEventListener("touchmove", onTouchMove, {
        passive: true,
      });
    }
  };

  document
    .querySelectorAll("[data-ermes-welcome]")
    .forEach((root) => void bindPopup(root));
})();
